# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios_notepad' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 5.0.0'
  pod 'GRDB.swift'

  # Pods for ios_notepad

  target 'ios_notepadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios_notepadUITests' do
    # Pods for testing
  end

end
